--- 
root_path: '/home/apolo2/Desktop/jart/src'
alt_wordlist: '/home/apolo2/SecLists/Discovery/DNS/bigger-alt.txt'
brute_wordlist: '/home/apolo2/SecLists/Discovery/DNS/dns-The-Biggest.txt'
resolvers: '/home/apolo2/.config/resolvers.txt'
trusted_resolvers: '/home/apolo2/.config/trusted_resolvers.txt'
db_host: 'localhost'
db_user: 'root'
db_pass: 'jart!'
max_http_redirection: 7
max_dns_retries: 3
max_http_retries: 3
http_req_timeout: 7
http_rcv_timeout: 12
max_http_size: 16000000
nuclei_templates: '/home/apolo2/nuclei-templates'
max_http_rps: 1200
nuclei_bulksize: 100
nuclei_concurrency: 30
max_http_probe_threads: 2048
max_dns_query_threads: 2048
dir_target_wordlists: True
dir_target_specific_path_depth: 1
dir_excluded_ext: 'ttf,woff,svg,png,jpg,ico,gif,html'
dir_wordlist_path: '/home/apolo2/SecLists/Discovery/Web-Content/medium-wl'
ferox_concurrency: 2048
http_proxy: "http://127.0.0.1:8080"
https_proxy: "https://127.0.0.1:8080"
