--- 
alt_wordlist: '/home/apolo2/SecLists/Discovery/DNS/small-alt.txt'
brute_wordlist: '/home/apolo2/SecLists/Discovery/DNS/dns-The-Biggest.txt'
domain: 'example.com'
resolvers: '/home/apolo2/.config/resolvers.txt'
db_host: 'localhost'
db_user: 'root'
db_pass: 'password_here'
scan_external_redirection: 0
max_http_redirection: 7
max_dns_retries: 3
max_http_retries: 3
http_req_timeout: 6
http_rcv_timeout: 12
max_http_size: 16000000
