--- 
alt_wordlist: '/home/apolo2/SecLists/Discovery/DNS/small-alt.txt'
brute_wordlist: '/home/apolo2/SecLists/Discovery/DNS/dns-The-Biggest.txt'
domain: 'example.com'
resolvers: '/home/apolo2/.config/resolvers.txt'
db_host: 'localhost'
db_user: 'root'
db_pass: 'pinkdog666'
